name: tekartik_serial_wss_client
description: A starting point for Dart libraries or applications.
version: 0.7.0-dev.2
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

dependencies:
  event_bus: any
  web_socket_channel: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.4.9'
  dart2_constant: any

dev_dependencies:
  test: any
  dev_test: any
  tekartik_test_menu_browser:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_browser
    version: '>=0.4.5'
  tekartik_test_menu_io:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_io
    version: '>=0.4.5'
  tekartik_serial_wss_sim:
    git:
      url: git://github.com/tekartik/serial_wss_sim.dart
      ref: dart2
    version: '>=0.3.0-dev.2'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2

dependency_overrides:
#  tekartik_serial_wss_sim:
#    path: ../serial_wss_sim.dart
