name: tekartik_serial_wss_client
description: A starting point for Dart libraries or applications.
version: 0.6.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  func: any
  event_bus: any
  web_socket_channel: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart1
    version: '>=0.4.9'
  dart2_constant: any

dev_dependencies:
  test: any
  dev_test: any
  tekartik_test_menu:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart1
    version: '>=0.4.5'
  tekartik_serial_wss_sim:
    git:
      url: git://github.com/tekartik/serial_wss_sim.dart
      ref: dart1
    version: '>=0.2.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1

dependency_overrides:
#  tekartik_serial_wss_sim:
#    path: ../serial_wss_sim.dart
