name: tekartik_serial_wss_client
description: A starting point for Dart libraries or applications.
version: 0.8.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.7.0-dev <3.0.0'

dependencies:
  event_bus: any
  web_socket_channel: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.3'
  dart2_constant: any
  tekartik_web_socket:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart2
    version: '>=0.1.0'

dev_dependencies:
  test: any
  dev_test: '0.13.2-dev.3'
  tekartik_test_menu_browser:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_browser
    version: '>=0.4.5'
  tekartik_test_menu_io:
    git:
      url: git://github.com/tekartik/test_menu.dart
      ref: dart2
      path: test_menu_io
    version: '>=0.4.5'
  tekartik_serial_wss_sim:
    git:
      url: git://github.com/tekartik/serial_wss_sim.dart
      ref: dart2
    version: '>=0.3.1'
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_io
      ref: dart2
    version: '>=0.1.0'
  tekartik_web_socket_browser:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket_browser
      ref: dart2
    version: '>=0.1.0'

  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: '>=0.9.0'
  build_test: '>=0.10.0'
  build_web_compilers: '>=0.4.2'
  process_run:

dependency_overrides:
#  tekartik_serial_wss_sim:
#    path: ../serial_wss_sim.dart
